package com.rlrg.dataserver.badge.entity;

//Generated May 22, 2014 3:25:47 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.rlrg.dataserver.badge.entity.enums.BadgeStatus;
import com.rlrg.dataserver.language.entity.BadgeLanguage;

/**
 * Badge generated by hbm2java
 */
@Entity
@Table(name = "badge")
public class Badge implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@Column(name = "status")
	private BadgeStatus status;

	@Column(name = "eligibility", length = 65535)
	private String eligibility;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "badge")
	private List<Achievement> achievements;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "badge")
	private List<BadgeLanguage> badgeLangs;

	public Badge() {
	}

	public Badge(String code, BadgeStatus status, String eligibility,
			List<Achievement> achievements) {
		this.status = status;
		this.eligibility = eligibility;
		this.achievements = achievements;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public BadgeStatus getStatus() {
		return this.status;
	}

	public void setStatus(BadgeStatus status) {
		this.status = status;
	}

	public String getEligibility() {
		return this.eligibility;
	}

	public void setEligibility(String eligibility) {
		this.eligibility = eligibility;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "badge")
	public List<Achievement> getAchievements() {
		return this.achievements;
	}

	public void setAchievements(List<Achievement> achievements) {
		this.achievements = achievements;
	}

}
