package com.rlrg.dataserver.language.entity;

// Generated May 22, 2014 3:25:47 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LangBad generated by hbm2java
 */
@Entity
@Table(name = "badge_language")
public class BadgeLanguage implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@Column(name = "badge_id", nullable = false)
	private Integer badge;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", nullable = false)
	private Language language;

	@Column(name = "name", length = 45)
	private String name;

	@Column(name = "description", length = 45)
	private String description;

	public BadgeLanguage() {
	}

	public BadgeLanguage(Integer badge, Language language) {
		this.badge = badge;
		this.language = language;
	}

	public BadgeLanguage(Integer badge, Language language, String name,
			String description) {
		this.badge = badge;
		this.language = language;
		this.name = name;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getBadge() {
		return this.badge;
	}

	public void setBadge(Integer badge) {
		this.badge = badge;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
