package com.rlrg.dataserver.language.entity;

// Generated May 22, 2014 3:25:47 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.rlrg.dataserver.task.entity.Category;

/**
 * LangCate generated by hbm2java
 */
@Entity
@Table(name = "lang_cate", catalog = "rlrg")
public class CategoryLanguage implements java.io.Serializable {

	private Integer id;
	private Language language;
	private Category category;
	private String cateName;
	private String discription;

	public CategoryLanguage() {
	}

	public CategoryLanguage(Language language, Category category) {
		this.language = language;
		this.category = category;
	}

	public CategoryLanguage(Language language, Category category, String cateName,
			String discription) {
		this.language = language;
		this.category = category;
		this.cateName = cateName;
		this.discription = discription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", nullable = false)
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "cate_name", length = 45)
	public String getCateName() {
		return this.cateName;
	}

	public void setCateName(String cateName) {
		this.cateName = cateName;
	}

	@Column(name = "discription", length = 65535)
	public String getDiscription() {
		return this.discription;
	}

	public void setDiscription(String discription) {
		this.discription = discription;
	}

}
