package com.rlrg.dataserver.language.entity;

// Generated May 22, 2014 3:25:47 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "language", catalog = "rlrg", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class Language implements java.io.Serializable {

	private int id;
	private String code;
	private String language;
	private String country;
	private String i18n;
	private Set<BadgeLanguage> badLangs = new HashSet<BadgeLanguage>(0);
	private Set<CategoryLanguage> cateLangs = new HashSet<CategoryLanguage>(0);

	public Language() {
	}

	public Language(int id, String code, String language) {
		this.id = id;
		this.code = code;
		this.language = language;
	}

	public Language(int id, String code, String language, String country,
			String i18n, Set<BadgeLanguage> badLangs, Set<CategoryLanguage> cateLangs) {
		this.id = id;
		this.code = code;
		this.language = language;
		this.country = country;
		this.i18n = i18n;
		this.badLangs = badLangs;
		this.cateLangs = cateLangs;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "code", unique = true, nullable = false, length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "language", nullable = false, length = 45)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "country", length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "i18n", length = 45)
	public String getI18n() {
		return this.i18n;
	}

	public void setI18n(String i18n) {
		this.i18n = i18n;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<BadgeLanguage> getBadLangs() {
		return this.badLangs;
	}

	public void setBadLangs(Set<BadgeLanguage> badLangs) {
		this.badLangs = badLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<CategoryLanguage> getCateLangs() {
		return this.cateLangs;
	}

	public void setCateLangs(Set<CategoryLanguage> cateLangs) {
		this.cateLangs = cateLangs;
	}

}
