package com.team.domain;
// Generated May 22, 2014 3:25:47 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="rlrg"
)
public class Category  implements java.io.Serializable {


     private Integer id;
     private Integer position;
     private Byte status;
     private Set<LangCate> langCates = new HashSet<LangCate>(0);
     private Set<Task> tasks = new HashSet<Task>(0);

    public Category() {
    }

    public Category(Integer position, Byte status, Set<LangCate> langCates, Set<Task> tasks) {
       this.position = position;
       this.status = status;
       this.langCates = langCates;
       this.tasks = tasks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="position")
    public Integer getPosition() {
        return this.position;
    }
    
    public void setPosition(Integer position) {
        this.position = position;
    }

    
    @Column(name="status")
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set<LangCate> getLangCates() {
        return this.langCates;
    }
    
    public void setLangCates(Set<LangCate> langCates) {
        this.langCates = langCates;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set<Task> getTasks() {
        return this.tasks;
    }
    
    public void setTasks(Set<Task> tasks) {
        this.tasks = tasks;
    }




}


